[package]
name = "ladex"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13"
actix-web = "4.0"
actix-web-actors = "4.3.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
env_logger = "0.11.8"
